-- require("nvim-tree").setup({ -- BEGIN_DEFAULT_OPTS
-- 	renderer = {
-- 		indent_markers = {
-- 			enable = true,
-- 		},
-- 	},
--     update_focused_file = {
--         enable = true
--     }
-- })
